name: action-tests
on: [push]
jobs:

  test:
    name: Test on go ${{ matrix.go_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: [1.13, 1.14]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Use Go ${{ matrix.go_version }}
      timeout-minutes: 3
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go_version }}
#      id: go

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Run tests
      run: go test -v -cover ./...
